# Generated by Django 6.1 on 2026-08-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Short description of the project')),
                ('technology', models.CharField(help_text='Comma separated list of technologies, e.g. Django, HTML, CSS', max_length=200)),
                ('github_link', models.URLField(help_text='Link to the public GitHub repository')),
                ('image', models.ImageField(blank=True, help_text='Optional screenshot / thumbnail for the project', null=True, upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
